# Generated by Django 3.2.10 on 2022-06-08 04:57

import attendence_sys.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('matricno', models.CharField(max_length=200, null=True)),
                ('program', models.CharField(choices=[('BIT', 'BIT'), ('BIP', 'BIP'), ('BIW', 'BIW'), ('BIS', 'BIS'), ('BIM', 'BIM')], max_length=200, null=True)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True)),
                ('section', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendence_sys.models.student_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(choices=[('Pengurusan Projek', 'Pengurusan Projek'), ('Pengurusan Perhubungan Pelanggan', 'Pengurusan Perhubungan Pelanggan'), ('Sistem Bantuan Keputusan', 'Sistem Bantuan Keputusan'), ('English for Higher Education', 'English for Higher Education'), ('Pengajian Islam', 'Pengajian Islam'), ('Pengajian Moral', 'Pengajian Moral'), ('Kenegaraan dan Pembangunan Mutakhir Malaysia', 'Kenegaraan dan Pembangunan Mutakhir Malaysia'), ('Prinsip Teknologi Maklumat', 'Prinsip Teknologi Maklumat'), ('Pengaturcaraan Komputer', 'Pengaturcaraan Komputer'), ('Struktur Diskrit', 'Struktur Diskrit'), ('Senibina Komputer', 'Senibina Komputer')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=15)),
                ('start', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='08:00', max_length=50)),
                ('end', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='10:00', max_length=50)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence_sys.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence_sys.student')),
                ('subname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence_sys.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence_sys.subject'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendence_sys.models.user_directory_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('matricno', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('program', models.CharField(max_length=200, null=True)),
                ('subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('section', models.CharField(max_length=200, null=True)),
                ('classday', models.CharField(blank=True, max_length=200, null=True)),
                ('classstart', models.CharField(blank=True, max_length=200, null=True)),
                ('classend', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='Absent', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
