# Generated by Django 3.2.10 on 2022-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(choices=[('Pengurusan Projek', 'Pengurusan Projek'), ('Pengurusan Perhubungan Pelanggan', 'Pengurusan Perhubungan Pelanggan'), ('Sistem Bantuan Keputusan', 'Sistem Bantuan Keputusan'), ('English for Higher Education', 'English for Higher Education'), ('Pengajian Islam', 'Pengajian Islam'), ('Pengajian Moral', 'Pengajian Moral'), ('Kenegaraan dan Pembangunan Mutakhir Malaysia', 'Kenegaraan dan Pembangunan Mutakhir Malaysia'), ('Prinsip Teknologi Maklumat', 'Prinsip Teknologi Maklumat'), ('Pengaturcaraan Komputer', 'Pengaturcaraan Komputer'), ('Struktur Diskrit', 'Struktur Diskrit'), ('Senibina Komputer', 'Senibina Komputer')], max_length=200, null=True),
        ),
    ]
