# Generated by Django 3.2.10 on 2022-06-08 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0003_auto_20220608_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
