# Generated by Django 3.2.10 on 2022-06-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0007_alter_student_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
    ]
