# Generated by Django 3.2.10 on 2022-06-08 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0008_auto_20220608_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='time',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
