# Generated by Django 3.2.10 on 2022-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0009_auto_20220608_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
