# Generated by Django 3.2.10 on 2022-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0012_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
