# Generated by Django 3.2.10 on 2022-06-08 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0014_alter_attendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(choices=[('Pengurusan Projek', 'Pengurusan Projek'), ('Pengurusan Perhubungan Pelanggan', 'Pengurusan Perhubungan Pelanggan'), ('Sistem Bantuan Keputusan', 'Sistem Bantuan Keputusan'), ('English for Higher Education', 'English for Higher Education'), ('Pengajian Islam', 'Pengajian Islam'), ('Pengajian Moral', 'Pengajian Moral'), ('Kenegaraan dan Pembangunan Mutakhir Malaysia', 'Kenegaraan dan Pembangunan Mutakhir Malaysia'), ('Prinsip Teknologi Maklumat', 'Prinsip Teknologi Maklumat'), ('Pengaturcaraan Komputer', 'Pengaturcaraan Komputer'), ('Struktur Diskrit', 'Struktur Diskrit'), ('Senibina Komputer', 'Senibina Komputer'), ('Falsafah Dan Isu Semasa', 'Falsafah Dan Isu Semasa'), ('Creativity & Innovation', 'Creativity & Innovation'), ('Sistem Maklumat Pengurusan', 'Sistem Maklumat Pengurusan'), ('Statistik', 'Statistik'), ('Kejuruteraan Perisian', 'Kejuruteraan Perisian'), ('Struktur Data dan Algoritma', 'Struktur Data dan Algoritma'), ('Essential Academic English', 'Essential Academic English'), ('Penghayatan, Etika dan Peradaban', 'Penghayatan, Etika dan Peradaban'), ('Interaksi Manusia-Komputer', 'Interaksi Manusia-Komputer'), ('Etika Profesional dan Keselamatan Pekerjaan', 'Etika Profesional dan Keselamatan Pekerjaan'), ('Analisis dan Rekabentuk Sistem', 'Analisis dan Rekabentuk Sistem'), ('Pengaturcaraan Berorientasikan Objek', 'Pengaturcaraan Berorientasikan Objek'), ('Sistem Pengoperasian', 'Sistem Pengoperasian'), ('Asas Keselamatan Maklumat', 'Asas Keselamatan Maklumat'), ('Pembangunan Web', 'Pembangunan Web'), ('Rangkaian dan Komunikasi Data', 'Rangkaian dan Komunikasi Data'), ('Sistem Pangkalan Data', 'Sistem Pangkalan Data'), ('Pengaturcaraan JAVA', 'Pengaturcaraan JAVA'), ('English for Technical Purposes', 'English for Technical Purposes'), ('Keusahawanan', 'Keusahawanan'), ('Pembangunan Aplikasi Mudah Alih', 'Pembangunan Aplikasi Mudah Alih'), ('Metodologi Penyelidikan Projek', 'Metodologi Penyelidikan Projek'), ('English for Occupational Purposes', 'English for Occupational Purposes'), ('Perancangan Sumber Enterprise', 'Perancangan Sumber Enterprise'), ('Projek Sarjana Muda', 'Projek Sarjana Muda'), ('Kecerdasan Buatan', 'Kecerdasan Buatan'), ('Pelombongan Data', 'Pelombongan Data'), ('Pembangunan Sistem Fuzzy', 'Pembangunan Sistem Fuzzy'), ('Pembelajaran Mesin', 'Pembelajaran Mesin'), ('Pembelajaran Mendalam', 'Pembelajaran Mendalam'), ('Sains Data', 'Sains Data')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectname',
            field=models.CharField(choices=[('Pengurusan Projek', 'Pengurusan Projek'), ('Pengurusan Perhubungan Pelanggan', 'Pengurusan Perhubungan Pelanggan'), ('Sistem Bantuan Keputusan', 'Sistem Bantuan Keputusan'), ('English for Higher Education', 'English for Higher Education'), ('Pengajian Islam', 'Pengajian Islam'), ('Pengajian Moral', 'Pengajian Moral'), ('Kenegaraan dan Pembangunan Mutakhir Malaysia', 'Kenegaraan dan Pembangunan Mutakhir Malaysia'), ('Prinsip Teknologi Maklumat', 'Prinsip Teknologi Maklumat'), ('Pengaturcaraan Komputer', 'Pengaturcaraan Komputer'), ('Struktur Diskrit', 'Struktur Diskrit'), ('Senibina Komputer', 'Senibina Komputer'), ('Falsafah Dan Isu Semasa', 'Falsafah Dan Isu Semasa'), ('Creativity & Innovation', 'Creativity & Innovation'), ('Sistem Maklumat Pengurusan', 'Sistem Maklumat Pengurusan'), ('Statistik', 'Statistik'), ('Kejuruteraan Perisian', 'Kejuruteraan Perisian'), ('Struktur Data dan Algoritma', 'Struktur Data dan Algoritma'), ('Essential Academic English', 'Essential Academic English'), ('Penghayatan, Etika dan Peradaban', 'Penghayatan, Etika dan Peradaban'), ('Interaksi Manusia-Komputer', 'Interaksi Manusia-Komputer'), ('Etika Profesional dan Keselamatan Pekerjaan', 'Etika Profesional dan Keselamatan Pekerjaan'), ('Analisis dan Rekabentuk Sistem', 'Analisis dan Rekabentuk Sistem'), ('Pengaturcaraan Berorientasikan Objek', 'Pengaturcaraan Berorientasikan Objek'), ('Sistem Pengoperasian', 'Sistem Pengoperasian'), ('Asas Keselamatan Maklumat', 'Asas Keselamatan Maklumat'), ('Pembangunan Web', 'Pembangunan Web'), ('Rangkaian dan Komunikasi Data', 'Rangkaian dan Komunikasi Data'), ('Sistem Pangkalan Data', 'Sistem Pangkalan Data'), ('Pengaturcaraan JAVA', 'Pengaturcaraan JAVA'), ('English for Technical Purposes', 'English for Technical Purposes'), ('Keusahawanan', 'Keusahawanan'), ('Pembangunan Aplikasi Mudah Alih', 'Pembangunan Aplikasi Mudah Alih'), ('Metodologi Penyelidikan Projek', 'Metodologi Penyelidikan Projek'), ('English for Occupational Purposes', 'English for Occupational Purposes'), ('Perancangan Sumber Enterprise', 'Perancangan Sumber Enterprise'), ('Projek Sarjana Muda', 'Projek Sarjana Muda'), ('Kecerdasan Buatan', 'Kecerdasan Buatan'), ('Pelombongan Data', 'Pelombongan Data'), ('Pembangunan Sistem Fuzzy', 'Pembangunan Sistem Fuzzy'), ('Pembelajaran Mesin', 'Pembelajaran Mesin'), ('Pembelajaran Mendalam', 'Pembelajaran Mendalam'), ('Sains Data', 'Sains Data')], max_length=200, null=True),
        ),
    ]
