# Generated by Django 3.2.10 on 2022-06-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0015_auto_20220608_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
