# Generated by Django 3.2.10 on 2022-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0016_attendence_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='actualattend',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendence',
            name='totalattend',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
