# Generated by Django 3.2.10 on 2022-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0017_auto_20220608_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='actualattend',
            field=models.IntegerField(null=True),
        ),
    ]
