# Generated by Django 3.2.10 on 2022-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0018_alter_attendence_actualattend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='actualattend',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='totalattend',
        ),
    ]
