# Generated by Django 4.0.5 on 2022-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0020_faculty_password1_faculty_password2_faculty_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='password1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='password2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
